language: c
before_install:
- curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
- chmod 755 ./travis-tool.sh
- "./travis-tool.sh bootstrap"
install:
- "./travis-tool.sh install_deps"
- "./travis-tool.sh install_r devtools microbenchmark knitr"
- "./travis-tool.sh install_r arules pbapply memoise stringr testthat"
- "./travis-tool.sh install_github robertzk/Ramd"
- "./travis-tool.sh install_github robertzk/testthatsomemore"
- "./travis-tool.sh install_github robertzk/stagerunner"
- "./travis-tool.sh install_github robertzk/statsUtils"
- "./travis-tool.sh install_github robertzk/mungebits"
- "./travis-tool.sh install_github robertzk/tundra"
- "./travis-tool.sh install_github robertzk/syberiaMungebits"
- "./travis-tool.sh install_github robertzk/syberiaStructure"
script: "./travis-tool.sh run_tests"
after_failure:
- "./travis-tool.sh dump_logs"
notifications:
  email:
    on_success: change
    on_failure: change
  hipchat:
    on_success: change
    on_failure: change
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}
      | Details: %{build_url} | Changes: %{compare_url}"
    rooms:
      secure: gG+IWZd2T1WGaqSAHqF9VM+BCJslXGtljDps92W+qMgA0i6mLXolMwwVReuPSLS1l2DM+zTh/bwPEXXa794NIYJBdXRVdSl5x3iHAlozPkVbn5kpCCkPMU95IxpdApl8vb9kIqly0tgLlQCLLULFvijUj50Z49XPvd51dmeQRgU=
